### ISSUE TITLE
Does nothing on OS X 10.9 with ST2 2.0.2

### ISSUE THREAD

**Issue by phs** [lefoy/AutomaticFullscreen#2]
OS X 10.9.5
Sublime Text 2 2.0.2 build 2221, default configuration, no other plugins.

When the application starts, my lone project window appears un-maximized.

Popping open the console and running `sublime.windows()[0].run_command("toggle_full_screen")` dutifully toggles the window in the expected way.

If I had to guess, I would suspect a race condition between the package execution and when ST2 (re)opens my project window.

**Comment by lefoy** [comment]
Thanks for letting me know! I'll take a look at this as soon as possible :)

**Comment by lefoy** [comment]
To be honest I didn't test the plugin with Sublime Text 2, could you please try it with ST3 and let me know if you still have this issue? That would help me a lot.

Thanks!

**Comment by phs** [comment]
I don't have a copy of ST3 handy, but if I happen on one I'll try and let you know.

**Comment by lefoy** [comment]
No problem. I think it might be a problem with ST2 because the code for this plugin is really simple. The only reason this plugin wouldn't work with ST2 is `plugin_loaded` module function.

**Comment by lefoy** [comment]
I just checked the API documentation for ST2 and it seems it doesn't support `plugin_loaded`. I'll try to find a way to make it work with ST2 asap.

**Comment by LeVM** [comment]
Any update on this? I'm using ST2, have downloaded this package but it doesn't work. Would love to use it if possible.
TIA

**Comment by lefoy** [comment]
Unfortunately, there is no clean way to run a plugin on ST2 startup... :\
I have no choice but to restrict this plugin for ST3 only, I'm sorry.

Ref: http://stackoverflow.com/questions/16177298/sublime-text-2-run-plugin-on-program-startup

**Comment by LeVM** [comment]
Hi,

Yes, I tried the new version and it didn't work. Pity, as it's a desirable feature.

Thanks, though, for trying.
